import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import ConfigureAmplify from './utils/configureAmplify';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Beta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className='dark'>
         <body className='bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 animate-drip-expand'>
              <ConfigureAmplify />
              <Providers>
                  {children}
              </Providers>
         </body>
    </html>
  )
}